//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_CTDP> tb_CTDP { get; set; }
        public virtual DbSet<tb_DATPHONG> tb_DATPHONG { get; set; }
        public virtual DbSet<tb_DATPHONG_DICHVU> tb_DATPHONG_DICHVU { get; set; }
        public virtual DbSet<tb_DICHVU> tb_DICHVU { get; set; }
        public virtual DbSet<tb_KHACHHANG> tb_KHACHHANG { get; set; }
        public virtual DbSet<tb_NHANVIEN> tb_NHANVIEN { get; set; }
        public virtual DbSet<tb_THANHTOAN> tb_THANHTOAN { get; set; }
        public virtual DbSet<tb_THIETBI> tb_THIETBI { get; set; }
        public virtual DbSet<tb_LOAIPHONG> tb_LOAIPHONG { get; set; }
        public virtual DbSet<tb_PHONG_THIETBI> tb_PHONG_THIETBI { get; set; }
        public virtual DbSet<tb_PHONG> tb_PHONG { get; set; }
    }
}
