//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_CTDP
    {
        public int MADP { get; set; }
        public int MAPHONG { get; set; }
        public int SONGUOI { get; set; }
        public System.DateTime NGAYNHAN { get; set; }
        public System.DateTime NGAYTRA { get; set; }
    }
}
