//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_NHANVIEN
    {
        public int MANV { get; set; }
        public string TENNV { get; set; }
        public bool CHUCVU { get; set; }
        public string ID { get; set; }
        public string PASSWORD { get; set; }
        public bool DISABLE { get; set; }
    }
}
