//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_PHONG
    {
        public int MAPHONG { get; set; }
        public string TENPHONG { get; set; }
        public bool TRANGTHAIPHONG { get; set; }
        public int MALP { get; set; }
        public Nullable<double> DONGIA { get; set; }
    }
}
